#!/bin/bash
source ~/.profile
source ~/.bashrc
source ~/shared.sh
source ~/production.sh

cd $HOME/$PROJECT_DIR

#https://www.freecodecamp.org/news/git-pull-force-how-to-overwrite-local-changes-with-git/
echo "FETCHING PRODUCTION"
git fetch
git reset --hard HEAD
git merge '@{u}'

echo "INSTALLING ELIXIR DEPENDANCIES"
mix deps.get
mix deps.compile

echo "INSTALL BUN PACKAGES"
bun install --verbose --production

echo "RESTARTING SERVICE"
SERV_ENABLED="$(systemctl is-enabled otterly.service)"

#reloads boot executables and their relationshipts on the system level (... I think)
#Got a warning without it, see systemctl man page near bottom.
systemctl daemon-reload

if [ "$SERV_ENABLED" == "enabled" ]; then
	systemctl restart otterly.service
	echo "SYSTEM RUNNING WEBSERVER"
else
	echo "NO WEBSERVER RUNNING"
fi
